//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelMvcProje.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEkibimiz
    {
        public int ID { get; set; }
        public string AdSoyad { get; set; }
        public string Unvan { get; set; }
        public string Gorsel { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
        public string LinkedIn { get; set; }
    }
}
