//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelMvcProje.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMailBulteni
    {
        public int ID { get; set; }
        public string Mail { get; set; }
    }
}
