//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelMvcProje.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMisafir
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMisafir()
        {
            this.TblRezervasyon = new HashSet<TblRezervasyon>();
        }
    
        public int MisafirID { get; set; }
        public string AdSoyad { get; set; }
        public string TC { get; set; }
        public string Mail { get; set; }
        public string Telefon { get; set; }
        public string Adres { get; set; }
        public string Aciklama { get; set; }
        public string KimlikFoto1 { get; set; }
        public string KimlikFoto2 { get; set; }
        public Nullable<int> Ulke { get; set; }
        public Nullable<int> Sehir { get; set; }
        public Nullable<int> Ilce { get; set; }
        public Nullable<int> Durum { get; set; }
        public string VarsayilanFoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblRezervasyon> TblRezervasyon { get; set; }
    }
}
